export const companies = [
  { name: "3Red Partners", url: "https://www.3redpartners.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "A Priori Investments", url: "https://www.aprioriinvestments.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Acadian Asset Management", url: "https://www.acadian-asset.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Akuna Capital", url: "https://akunacapital.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Albatross Labs", url: "https://www.albatrosslabs.io/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "AlphaGrep", url: "https://www.alpha-grep.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "AlphaSimplex", url: "https://www.alphasimplex.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Alyeska Investment Group", url: "https://www.alyeskagroup.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "AQR Capital Management", url: "https://www.aqr.com/About-Us/Careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Aquatic Capital", url: "https://www.aquatic.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Arrowstreet Capital", url: "https://www.arrowstreetcapital.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Aspect Capital", url: "https://www.aspectcapital.com/about/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Atto Trading", url: "https://atto-trading.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Balyasny Asset Management", url: "https://www.bamfunds.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Belvedere Trading", url: "https://www.belvederetrading.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "BlackEdge Capital", url: "https://www.blackedge.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Bluefin Capital Management", url: "https://www.bfcm.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Boerboel Trading", url: "https://www.boerboeltrading.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Brevan Howard", url: "https://www.brevanhoward.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Bridgewater Associates", url: "https://www.bridgewater.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Cantor Fitzgerald", url: "https://www.cantor.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Capital Fund Management", url: "https://www.cfm.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Capstone", url: "https://www.capstoneco.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Caxton Associates", url: "https://www.caxton.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Centiva Capital", url: "https://centivacapital.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Chicago Trading Company", url: "https://www.chicagotrading.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Citadel", url: "https://www.citadel.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Consolidated Trading", url: "http://prod.consolidatedtrading.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "CQS", url: "https://www.cqs.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Cubist (Point72)", url: "https://careers.point72.com/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "DE Shaw", url: "https://www.deshaw.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "DRW", url: "https://drw.com/work-at-drw/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "DV Trading", url: "https://dvtrading.co/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Edgestream Partners", url: "https://www.edgestreamlp.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Eisler Capital", url: "https://eislercapital.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Emergent Trading", url: "https://www.emergenttrading.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Engineers Gate", url: "https://www.eglp.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Eqvilent", url: "https://www.eqvilent.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "ExodusPoint", url: "https://www.exoduspoint.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Five Rings", url: "https://fiverings.com/apply/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Florin Court Capital", url: "https://florincourt.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Flow Traders", url: "https://www.flowtraders.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "G-Research", url: "https://www.gresearch.com/vacancies/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "GAM Systematic", url: "https://www.gam.com/en/about-us/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Garda Capital Partners", url: "https://www.gardacp.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Gelber Group", url: "https://www.gelbergroup.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Geneva Trading", url: "https://www.genevatrading.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Geode Capital Management", url: "https://www.geodecapital.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Graham Capital Management", url: "https://www.grahamcapital.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Graviton Research Capital", url: "https://www.gravitontrading.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Group One Trading", url: "https://group1.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "GSA Capital Partners", url: "https://www.gsacapital.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "GTS", url: "https://gtsx.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "HAP Capital", url: "https://www.hap-capital.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Headlands Technologies", url: "https://www.headlandstech.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Hudson Bay Capital", url: "https://www.hudsonbaycapital.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Hudson River Trading", url: "https://www.hudsonrivertrading.com/career-opportunities/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "IMC Financial Markets", url: "https://www.imc.com/us/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Jacobs Levy Equity Management", url: "https://www.jlem.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Jane Street", url: "https://www.janestreet.com/join-jane-street/open-roles/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Jump Trading", url: "https://www.jumptrading.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Kepos Capital", url: "https://www.keposcapital.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Laurion Capital Management", url: "https://www.laurioncap.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Man Group", url: "https://www.man.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Mana Partners", url: "https://www.mana-partners.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Marshall Wace", url: "https://www.mwam.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Maven Securities", url: "https://www.mavensecurities.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Millburn", url: "https://millburn.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Old Mission Capital", url: "https://www.oldmissioncapital.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Optiver", url: "https://optiver.com/working-at-optiver/career-opportunities/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "PanAgora", url: "https://www.panagora.com/about/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "PDT Partners", url: "https://pdtpartners.com/careers.html", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Peak6", url: "https://peak6.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "PGIM Quant Solutions", url: "https://jobs.pgim.com/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "QMS Capital Management", url: "https://www.qmscapital.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Quadrature", url: "https://quadrature.ai/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Quantbot Technologies", url: "https://www.quantbot.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Quantlab Financial", url: "https://www.quantlab.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Qube Research & Technologies", url: "https://www.qube-rt.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Radix Trading", url: "https://radixtrading.co/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Renaissance Technologies", url: "https://www.rentec.com/Careers.action", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Rokos Capital Management", url: "https://www.rokoscapital.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "RSJ", url: "https://www.rsj.com/en/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Schonfeld Strategic Advisors", url: "https://www.schonfeld.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Seven Eight Capital", url: "https://www.seveneightcapital.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Simplex Trading", url: "https://simplextrading.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Squarepoint Capital", url: "https://www.squarepoint-capital.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Stevens Capital Management", url: "https://www.scm-lp.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Summit Securities Group", url: "https://www.ssgllc.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Susquehanna International Group", url: "https://sig.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Systematica Investments", url: "https://www.systematica.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Teza Technologies", url: "https://www.teza.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "TGS Management Company", url: "https://www.tgsmc.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Tower Research Capital", url: "https://www.tower-research.com/open-positions", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Tradebot", url: "https://www.tradebot.com/jobs.html", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "TransMarket Group", url: "https://www.transmarketgroup.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Trexquant Investment", url: "https://trexquant.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Two Sigma", url: "https://www.twosigma.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Verition Fund Management", url: "https://www.verition.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Virtu Financial", url: "https://www.virtu.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Voleon Group", url: "https://voleon.com/careers.html", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Voloridge Investment Management", url: "https://www.voloridge.com/join", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Walleye Capital", url: "https://walleyecapital.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "WH Trading", url: "https://whtrading.com/careers/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Winton Capital Management", url: "https://www.winton.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Wintermute", url: "https://www.wintermute.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "Wolverine Trading", url: "https://www.wolve.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "WorldQuant", url: "https://www.worldquant.com/career-listing/", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "XR Trading", url: "https://www.xrtrading.com/careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" },
  { name: "XTX Markets", url: "https://www.xtxmarkets.com/#careers", selector: "h1, h2, h3, h4, .job-title, .posting-title" }
];
